### ISSUE TITLE
Routes web services must return the link to the the schedule

### ISSUE THREAD

**Issue by rikyfocil-old** [PhysicsApp/etecapp#12]
The link is vital to display the schedule. The affected routes are
- mobileLogin
- getAllRoutes

This will have an impact in the following platforms 
- web service
- iOS App

@AliGhahraei When fixed please assign myself ( @rikyfocil ) to fix the second part

**Comment by AliGhahraei** [comment]
Oopsy daisy

**Comment by rikyfocil** [comment]
Web service verified so the issue may remain closed
