### ISSUE TITLE
Web service does not handle lower case letters

### ISSUE THREAD

**Issue by rikyfocil-old** [PhysicsApp/etecapp#16]
For ITESM accounts 

a01327311 == A01327311

But the web service rejects the first option.
### Possible solution

Apply a to upper case on the registry form and in the mobile login parameter

This solution will have to be applied in the upcoming drivers login route

**Comment by AliGhahraei** [comment]
This would affect all non-student users. Please validate it from the client, as the server makes no distinction, @rikyfocil.
